bot:
    token: 1986247174:AAGj8iSxr_KzlqbVJPA6iMQbVjdURPxfGLA
    parse_mode: html

executor:
    skip_updates: true

modules:
    - handlers.main
    - handlers.errors

log_ignore:
    - aiogram
    - asyncio
    - aiogram.Middleware

commands:
    start: Начать беседу со мной
